# Generated by Django 3.0.7 on 2020-06-28 14:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('site_url', models.CharField(blank=True, max_length=255, null=True)),
                ('feed_url', models.CharField(max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_polled', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('due_poll', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('last_modified', models.CharField(blank=True, max_length=255, null=True)),
                ('last_result', models.CharField(blank=True, max_length=255, null=True)),
                ('interval', models.PositiveIntegerField(default=400)),
                ('last_success', models.DateTimeField(null=True)),
                ('last_change', models.DateTimeField(null=True)),
                ('live', models.BooleanField(default=True)),
                ('status_code', models.PositiveIntegerField(default=0)),
                ('last_302_url', models.CharField(blank=True, max_length=255, null=True)),
                ('last_302_start', models.DateTimeField(blank=True, null=True)),
                ('max_index', models.IntegerField(default=0)),
                ('num_subs', models.IntegerField(default=1)),
                ('is_cloud_flare', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('link', models.CharField(blank=True, max_length=512, null=True)),
                ('found', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(db_index=True)),
                ('uuid', models.CharField(db_index=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='feed.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
