VERIFICATION_TEXT_TYPE_EMAIL_VERIFICATION = 'email_verification'
VERIFICATION_TEXT_TYPE_PASSWORD_VERIFICATION = 'password_verification'

VERIFICATION_TEXT_TYPE_CHOICES = (
    (VERIFICATION_TEXT_TYPE_EMAIL_VERIFICATION, 'Email Verification'),
    (VERIFICATION_TEXT_TYPE_PASSWORD_VERIFICATION, 'Password Verification'),
)
